# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simon's two-stage rules 
#' @export
bacSimonSingle <- function(y, n1, r1, n, r, bsize, rst) {
    invisible(.Call(`_basim_bacSimonSingle`, y, n1, r1, n, r, bsize, rst))
}

#' Search r1 and r given n1 and n
#' @export
bacSimonSearchR <- function(y0, y1, n1, n, bsize, alpha, beta, optimal) {
    invisible(.Call(`_basim_bacSimonSearchR`, y0, y1, n1, n, bsize, alpha, beta, optimal))
}

#' Simon's two-stage design 
#' @export
bacSimonDesign <- function(y0, y1, nmax, nmin, bsize, alpha, beta) {
    .Call(`_basim_bacSimonDesign`, y0, y1, nmax, nmin, bsize, alpha, beta)
}

#' Get InterClass Correlation
#' @export
bacICC <- function(ys, bsizes) {
    .Call(`_basim_bacICC`, ys, bsizes)
}

